site:
  about:
    siteName: 'The Para Guide'
    subtitle: 'The one stop shop for death, fun times, and eve.'
    siteDescription: 'Para Guide, we maybe know what are doing.'
    avatar: '/assets/media/logo.jpg'
  theme: 'FutureImperfect'
  baseUrl: 'netlify'

theme:
  social:
    github: 'roflush'
  menu:
    - type: 'page'
      title: 'Home'
      url: '/'
    - type: "wikiSections"
    - type: 'taxonomy'
      taxonomyType: 'categories'
      includeTerms: true
      termsAtRoot: true
    - type: 'page'
      title: 'guest post'
      itemId: 'guest'
    - type: "pages"
      atRoot: true
    - type: groupPages
      collectionType: pages
      collectionId: allPages
  sidebar:
    - type: recentPosts
      limit: 3
      category: gallery
      noWrapper: true
      template:
        - 'includes/postPreview_mini'
    - type: recentPosts
      limit: 5
      category: personal
      noWrapper: true
      template:
        - 'includes/postPreview_list'
  extraCss:
    - 'assets/css/extraCss.scss'
    - 'assets/css/pygments.scss'
  extraJs:
    - 'assets/js/extraJs.js'
  legacySearch: false
  metaComponents:
    - type: orchidSearch

services:
  generators:
    externalIndices:
      - 'https://orchid.run/meta/all.index.json'
