permalink: ':category/:year/:monthName/:slug'
categories:
  - key: 'eve'
    title: 'EVE Online'
  - key: 'gaming'
    title: 'Gaming'
  - key: 'random'
    title: 'Random'
authors:

postPages:
  author: ' '
  layout: single
  components:
    - type: pageContent
    - type: taxonomy
      taxonomyType: tags
    - type: taxonomy
      taxonomyType: categories
